name: laundry3b1titik0
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  http: ^1.2.1
  dio: ^5.4.3+1
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  supabase_flutter: ^2.5.0
  intl: ^0.20.2
  geolocator: ^9.0.2
  flutter_map: ^6.0.0
  latlong2: ^0.9.1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  

  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0

# Konfigurasi Icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_3b.png"
  min_sdk_android: 21

# Konfigurasi Splash Screen
flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo_3b.png"
  android_12:
    image: "assets/images/logo_3b.png"
    icon_background_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/